version: "3.7"

services:
  app:
    build: .
    env_file:
      - .env
    container_name: form_app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8888:8000
    depends_on:
      - mongo_db
  
  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - 27018:27017
    env_file:
      - .env
    volumes:
      - "./data:/data/db"

  mongo_seed:
    build: ./mongo
    depends_on:
      - mongo_db
    environment:
      - db_host=mongo_db
      - db_name=form_templates
